name: continuous-integration
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.5
      id: go
    
    - name: Setup Terraform environment
      uses: marocchino/setup-terraform@v1.0.1
      with:
        # The terraform version to download (if necessary) and use. Example: 0.12.13
        version: 0.12.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: |
        echo `ls -l`
        export GO111MODULE=on
        go mod download

    - name: Build
      run: |
        echo `pwd`
        go test -v -timeout 90m  yugabyte_test.go
