name: continuous-integration
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Google Cloud Platform (GCP) CLI - gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '275.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - run: gcloud info 

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.5
      id: go
    
    - name: Setup Terraform environment
      uses: marocchino/setup-terraform@v1.0.1
      with:
        # The terraform version to download (if necessary) and use. Example: 0.12.13
        version: 0.12.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Get dependencies
      run: |
        cd ./test
        go mod init test
        go mod download

    - name: Build
      run: |
        cd ./test
        echo "$gcp" 
        echo "$gcp" | base64 --decode > ${HOME}/key.json
        cat ${HOME}/key.json
        export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/key.json"
        go test -v -timeout 90m  yugabyte_test.go
        rm ${HOME/key.json}
